version: "3.9"

services:
  server:
    build: .
    container_name: django-graphene
    image: django/graphene
    volumes:
      - .:/app
    ports:
      - "8000:8001"
    command: python manage.py runserver 0.0.0.0:8001
