# Generated by Django 4.2.3 on 2024-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, upload_to="books_images/"),
        ),
    ]
